---
author: Thomas Fauroux
description: Installation de MetalLB (load balancer bare-metal) via Helm
license: MIT
min_ansible_version: "2.15"
platforms:
  - name: EL
    versions: ["9"]
dependencies: []
