apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.16.2
    helm:
      valuesObject:
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: harbor-tls
          ingress:
            hosts:
              core: harbor.k8s.yplank.fr
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
        externalURL: https://harbor.k8s.yplank.fr
        harborAdminPassword: "Ch4ng3M3!"
        # Stratégie Recreate pour les composants avec PVC RWO
        registry:
          updateStrategy:
            type: Recreate
          nodeSelector:
            kubernetes.io/hostname: rncp-scw-worker-01
        jobservice:
          updateStrategy:
            type: Recreate
        core:
          nodeSelector:
            kubernetes.io/hostname: rncp-scw-worker-01
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: scw-bssd
              size: 10Gi
            database:
              storageClass: scw-bssd
              size: 2Gi
            redis:
              storageClass: scw-bssd
              size: 1Gi
            jobservice:
              jobLog:
                storageClass: scw-bssd
                size: 1Gi
            trivy:
              storageClass: scw-bssd
              size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true