apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.142
    helm:
      valuesObject:
        controller:
          admin:
            password: "Ch4ng3M3!"
          nodeSelector:
            kubernetes.io/hostname: rncp-scw-worker-02
          ingress:
            enabled: true
            ingressClassName: nginx
            hostName: jenkins.k8s.yplank.fr
            tls:
              - secretName: jenkins-tls
                hosts:
                  - jenkins.k8s.yplank.fr
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 2Gi
          installPlugins:
            - kubernetes:4423.vb_59f230b_ce53
            - workflow-aggregator:608.v67378e9d3db_1
            - git:5.10.0
            - configuration-as-code:2037.v8e5349845172
          additionalPlugins:
            - gitlab-plugin:latest
            - sonar:latest
            - docker-workflow:latest
            - blueocean:latest
            - pipeline-stage-view:latest
        persistence:
          enabled: true
          storageClass: scw-bssd
          size: 10Gi
        agent:
          enabled: true
          # Forcer les agents de build sur worker-01 (29% RAM utilisée)
          # worker-02 est à 84% et ne supporterait pas un build
          nodeSelector:
            kubernetes.io/hostname: rncp-scw-worker-01
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true