---
- name: Ajouter le repo Helm ingress-nginx
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Créer le namespace ingress-nginx
  kubernetes.core.k8s:
    name: "{{ ingress_nginx_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Installer Ingress NGINX
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_nginx_chart_version }}"
    release_namespace: "{{ ingress_nginx_namespace }}"
    values:
      controller:
        replicaCount: 1
        service:
          type: LoadBalancer
        ingressClassResource:
          default: true
    wait: true
    wait_timeout: "300s"

- name: Attendre que le contrôleur Ingress soit prêt
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ ingress_nginx_namespace }}"
    name: ingress-nginx-controller
    wait: true
    wait_timeout: 120
    wait_condition:
      type: Available
      status: "True"

- name: Récupérer l'IP externe de l'Ingress Controller
  kubernetes.core.k8s_info:
    kind: Service
    namespace: "{{ ingress_nginx_namespace }}"
    name: ingress-nginx-controller
  register: ingress_svc

- name: Afficher l'IP de l'Ingress Controller
  ansible.builtin.debug:
    msg: "Ingress Controller IP : {{ ingress_svc.resources[0].status.loadBalancer.ingress[0].ip }}"
  when: ingress_svc.resources[0].status.loadBalancer.ingress is defined
