---
- name: Ajouter le repo Helm Scaleway
  kubernetes.core.helm_repository:
    name: scaleway
    repo_url: https://scaleway.github.io/helm-charts

- name: Installer scaleway-csi
  kubernetes.core.helm:
    name: scaleway-csi
    chart_ref: scaleway/scaleway-csi
    chart_version: "{{ scaleway_csi_chart_version }}"
    release_namespace: kube-system
    values:
      controller:
        scaleway:
          existingSecretName: scaleway-secret
      node:
        scaleway:
          existingSecretName: scaleway-secret
      storageClass:
        defaultClass: true
    wait: true
    wait_timeout: "300s"

- name: Vérifier que scaleway-csi est prêt
  kubernetes.core.k8s_info:
    kind: DaemonSet
    namespace: kube-system
    name: scaleway-csi-node
    wait: true
    wait_timeout: 120
    wait_condition:
      type: Available
      status: "True"
  ignore_errors: true
