---
author: Thomas Fauroux
description: Installation de kubeadm, kubelet et kubectl via le repo officiel Kubernetes
license: MIT
min_ansible_version: "2.15"
platforms:
  - name: EL
    versions: ["9"]
dependencies: []
