all:
  children:
    control_plane:
      hosts:
        rncp-cp-01:

    workers:
      hosts:
        rncp-worker-01:
        rncp-worker-02:

    k8s_cluster:
      children:
        control_plane:
        workers: