---
author: Thomas Fauroux
description: Installation de cert-manager avec emetteur Let's Encrypt (DNS challenge OVH)
license: MIT
min_ansible_version: "2.15"
platforms:
  - name: EL
    versions: ["9"]
dependencies: []
